[template]
cargo_generate_version = ">=0.23.0"
ignore = ["build", "compile_commands.json", "README.md", "CONTRIBUTING.md", "LICENSE"]

[placeholders]
project_description = { type = "string", prompt = "Project description", default = "C++26 module project using cpp-core" }
